services:

  account-management-service:
    build:
      context: ./account-management-service
    depends_on:
      - consul
      - api-gateway
    restart: always

  inventory-service:
    build:
      context: ./inventory-service
    depends_on:
      - consul
      - api-gateway
    restart: always

  order-service:
    build:
      context: ./order-service
    depends_on:
      - consul
      - api-gateway
      - inventory-service
    restart: always

  notification-service:
    build:
      context: ./notification-service
    depends_on:
      - consul
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - consul

  consul:
    container_name: consul
    image: consul:1.11
    ports:
      - "8500:8500"
    restart: always