services:

  account-management-service:
    build:
      context: ./account-management-service
    depends_on:
      - consul
      - api-gateway
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  product-service:
    build:
      context: ./product-service
    depends_on:
      - consul
      - api-gateway
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  order-service:
    build:
      context: ./order-service
    depends_on:
      - consul
      - api-gateway
      - product-service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  notification-service:
    build:
      context: ./notification-service
    depends_on:
      - consul
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - consul
    environment:
      SPRING_PROFILES_ACTIVE: docker

  consul:
    container_name: consul
    image: consul:1.11
    ports:
      - "8500:8500"
    restart: always