server:
  port: 0

spring:
  application:
    name: order-service
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${random.int}